version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"    # Expose React app locally at http://localhost:3000
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # API accessible locally at http://localhost:8080
    environment:
      - ENV=development

