version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  payments:
    build:
      context: ./services/payments
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

