name: Build and Push to ECR

on:
  push:
    branches: [develop]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'services/**'
      - '.github/workflows/ci-ecr-push.yml'

jobs:
  docker-build-and-push:
    name: Build & Push Docker Images to ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push Backend
        run: |
          docker build -t $ECR_REGISTRY/fullstack-backend:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/fullstack-backend:$IMAGE_TAG

      - name: Build & Push Frontend
        run: |
          docker build -t $ECR_REGISTRY/fullstack-frontend:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/fullstack-frontend:$IMAGE_TAG

      - name: Build & Push Auth
        run: |
          docker build -t $ECR_REGISTRY/fullstack-auth:$IMAGE_TAG ./services/auth
          docker push $ECR_REGISTRY/fullstack-auth:$IMAGE_TAG

      - name: Build & Push Payments
        run: |
          docker build -t $ECR_REGISTRY/fullstack-payments:$IMAGE_TAG ./services/payments
          docker push $ECR_REGISTRY/fullstack-payments:$IMAGE_TAG
